.de FN
\fI\|\\$1\|\fP\\$2
..
.TH punch 23 "July 2015"
.SH NAME
punch \- work-diary punch card

.SH SYNOPSIS
.B punch
.RB [ \-bnt ]
.RB [ \- chms
.RB NUMBER ]

.SH DESCRIPTION
.B punch
reads work diary from standard input and prints punch card to the standard output.
It uses convert table to transfer each label to one letter mark that will be print out (see config.h).

.SH OPTIONS
.TP
.BI \-b
Print both, hours and symbols.
.TP
.BI \-n
Print number part.
.TP
.BI \-t
Print times. It makes sense only in conjunction with -n or -b.
.TP
.BI \-c " COLUMNS"
Number of COLUMNS to print.
.TP
.BI \-h " HOUR"
Bin size in hours.
.TP
.BI \-m " MIN"
Bin size in minutes.
.TP
.BI \-s " SEC"
Bin size in seconds.

.SH AUTHORS
Copyright \(co 2015 by Petr Vaněk <arkamar@atlas.cz>
