.Dd August 7, 2015
.Dt PUNCH 1
.Os wd
.Sh NAME
.Nm punch
.Nd work-diary punch card
.Sh SYNOPSIS
.Nm
.Op Fl bnt
.Op Fl chms Ar NUMBER
.Sh DESCRIPTION
.Nm
reads work diary from standard input and prints punch card to the standard output.
It converts each label to a letter defined in convert table (see config.h).
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl b
Print both, hours and symbols.
.It Fl n
Print number part.
.It Fl t
Print times. It makes sense only in conjunction with -n or -b.
.It Fl c Ar COLUMNS
Number of COLUMNS to print.
.It Fl h Ar HOURS
Bin size in hours.
.It Fl m Ar MIN
Bin size in minutes.
.It Fl s Ar SEC
Bin size in seconds.
.El
.Sh AUTHORS
Copyright \(co 2015 by Petr Vaněk <arkamar@atlas.cz>
.Sh BUGS
Pleas report them.
.Sh SEE ALSO
.Xr stat 1
