.Dd August 7, 2015
.Dt STAT 1
.Os wd
.Sh NAME
.Nm stat
.Nd work-diary statistics
.Sh SYNOPSIS
.Nm
.Op Fl dmtw
.Op Fl ceM Ar NUMBER
.Sh DESCRIPTION
.Nm
reads work diary from standard input and prints statistics to the standard output.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c Ar COLUMNS
Number of columns to print.
.It Fl d
Print day status for previous day when new day starts.
.It Fl e Ar EFFICIENCY
Working efficiency in percent.
.It Fl M Ar MONEY
Money per hour.
.It Fl m
Print month status for previous month when new month starts.
.It Fl t
Print tasks.
.It Fl w
Print week status for previous week when new week starts.
.It Fl W Ar LABEL
It sets working label used to compute salary and working hours.
.El
.Sh AUTHORS
Copyright \(co 2015 by Petr Vaněk <arkamar@atlas.cz>
.Sh BUGS
Pleas report them.
.Sh SEE ALSO
.Xr punch 1
