.Dd August 7, 2015
.Dt WRKHR 1
.Os wd
.Sh NAME
.Nm wrkhr
.Nd work-diary statistics
.Sh SYNOPSIS
.Nm
.Op Fl dhlprt
.Op Fl W Ar LABEL
.Op Fl eM Ar NUMBER
.Sh DESCRIPTION
.Nm
.Sh OPTIONS
.Bl -tag -width Ds
.El
.Sh AUTHORS
Copyright \(co 2015 by Petr Vaněk <arkamar@atlas.cz>
.Sh BUGS
Pleas report them.
